{% set version = "0.1.18" %}

package:
  name: uv
  version: {{ version }}

source:
  fn: uv-{{ version }}.tar.gz
  url: https://github.com/astral-sh/uv/releases/download/{{ version }}/source.tar.gz
  sha256: 87d953dc58d3936c299609b1697b6d17ca85407edc177d293c98bb9451f8e5ff

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make

test:
  requires:
    - m2-grep  # [win]
  commands:
    - uv --version
    - uv --help
    - uv --version | grep -iE "{{ version.replace('.', '\.') }}"

about:
  home: https://github.com/astral-sh/uv
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An extremely fast Python package installer and resolver, written in Rust.

extra:
  recipe-maintainers:
    - charliermarsh
    - bollwyvl
