{% set version = "0.2.4" %}

package:
  name: uv
  version: {{ version }}

source:
  fn: uv-{{ version }}.tar.gz
  url: https://github.com/astral-sh/uv/releases/download/{{ version }}/source.tar.gz
  sha256: 073532db6eaf44da32d9a9536f6c48f1c8d450340969234a1b6ac322811758d4

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make

test:
  requires:
    - m2-grep  # [win]
  commands:
    - uv --version
    - uv --help
    - uv --version | grep -iE "{{ version.replace('.', '\.') }}"

about:
  home: https://github.com/astral-sh/uv
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An extremely fast Python package installer and resolver, written in Rust.

extra:
  recipe-maintainers:
    - charliermarsh
    - bollwyvl
