{% set version = "0.1.13" %}

package:
  name: uv
  version: {{ version }}

source:
  fn: uv-{{ version }}.tar.gz
  url: https://github.com/astral-sh/uv/releases/download/{{ version }}/source.tar.gz
  sha256: 859b13879d2a6f97c3c4d8928cb6a81b067b022b4e5b6c8e75bba099570bd0fe

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make

test:
  requires:
    - m2-grep  # [win]
  commands:
    - uv --version
    - uv --help
    - uv --version | grep -iE "{{ version.replace('.', '\.') }}"

about:
  home: https://github.com/astral-sh/uv
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An extremely fast Python package installer and resolver, written in Rust.

extra:
  recipe-maintainers:
    - bollwyvl
